In [ ]:
# importing libraries for data manipulation , processing and analysis libraries
import numpy as np
import numpy.random as random
import scipy as sp
import pandas as pd
from pandas import Series,DataFrame

# libraries for data visualisation
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
%matplotlib inline

#Machine learning library
import sklearn
#To display up to three decimal places
%precision 3

'%.3f'

In [ ]:
# Import
import requests, zipfile
import io

# Fetching automobile price data
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
res = requests.get(url).content

# Loading  the fetched data into a DataFrame object
auto = pd.read_csv(io.StringIO(res.decode('utf-8')), header=None)

# Setting  labels for the data columns
auto.columns =['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration', 'num-of-doors',
                            'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length', 'width', 'height',
                            'curb-weight', 'engine-type', 'num-of-cylinders', 'engine-size', 'fuel-system', 'bore',
                            'stroke', 'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price']

In [ ]:
# checking the type of data rows and coloums respectively
print('Shape of the car data:{}'.format (auto.shape))

auto.head() # displaying the first five rows

Shape of the car data:(205, 26)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [ ]:
# Processing the data
# Using horsepower , width and height as the explanatory variables

# counting the number of ? in the dataset
auto=auto[['price','horsepower','width','height']]
auto.isin(['?']).sum()


# Replacing "?" with NaN and drops down with NaN
auto= auto.replace('?',np.nan).dropna()
print('shape of the car data:{}'.format(auto.shape)) # the number of rows have reduced

#checking the data types before type conversion
print('Check data types\n{}\n'.format(auto.dtypes))

shape of the car data:(199, 4)
Check data types
price          object
horsepower     object
width         float64
height        float64
dtype: object

In [ ]:
# converting the object data types to numeric values
auto= auto.assign(price=pd.to_numeric(auto.price))
auto= auto.assign(horsepower=pd.to_numeric(auto.horsepower))
auto= auto.assign(width=pd.to_numeric(auto.width))

#correlation check
auto.corr()

               price  horsepower     width    height
price       1.000000    0.810533  0.753871  0.134990
horsepower  0.810533    1.000000  0.615315 -0.087407
width       0.753871    0.615315  1.000000  0.309223
height      0.134990   -0.087407  0.309223  1.000000

In [ ]:
from re import X
#Library for splitting  the data into training data and testing data
from sklearn.model_selection import train_test_split

#import for buidling the multiple regression model
from sklearn.linear_model import LinearRegression

#Setting price as the target variable and the rest as explanatory
x =auto.drop('price',axis=1)
y =auto['price']

#Actual splitting
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.5, random_state=0)

#initializing and training the model
model=LinearRegression()
model.fit(X_train,y_train)

#Displaying the coefficient of determinnation
print('coefficient of determination(train):{:.3f}'.format(model.score(X_train,y_train)))
print('coefficient of determination(test):{:.3f}'.format(model.score(X_test,y_test)))

#Displaying regression coefficients and intercept
print('\nRegression coefficient\n{}'.format(pd.Series(model.coef_,index=x.columns)))
print('\nRegression intercept:{:.3f}'.format(model.intercept_))

coefficient of determination(train):0.733
coefficient of determination(test):0.737

Regression coefficient
horsepower      81.651078
width         1829.174506
height         229.510077
dtype: float64

Regression intercept:-128409.046

In [ ]:
# Retrieve the data
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data'
res = requests.get(url).content

# Load the retrieved data as a DataFrame object
adult = pd.read_csv(io.StringIO(res.decode('utf-8')), header=None)

# Set column labels for the data
adult.columns = ['age', 'workclass', 'fnlwgt', 'education', 'education-num', 'marital-status',
                             'occupation', 'relationship', 'race', 'sex', 'capital-gain', 'capital-loss', 'hours-per-week',
                             'native-country', 'flg-50K']


# Output the data's shape and missing values
print('Data Format:{}'.format(adult.shape))
print('Number of defects:{}'.format(adult.isnull().sum().sum()))

# Output the first 5 rows of the data
adult.head()

Data Format:(32561, 15)
Number of defects:0

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,flg-50K
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [ ]:
# Data Preparation
adult.groupby('flg-50K').size()   #Converting this variables into 0 and 1

#There are 24720 and 7841 rows of with <= 50 and = 50

#Adding a coloumn named 'fin_flag' coloumn and setting it to 1 if the value of the is >50k
adult['fin_flg']=adult['flg-50K'].map(lambda x: 1 if x.strip() == '>50K' else 0)
adult.groupby('fin_flg').size()

fin_flg
0    24720
1     7841
dtype: int64

In [ ]:
# Model construction and Evaluation
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

#importing the class for Standardization
from sklearn.preprocessing import StandardScaler

#Setting explanatory variables and target variable
X = adult[['age','fnlwgt','education-num','capital-gain','capital-loss','hours-per-week']]
y = adult['fin_flg']

#Standardizing the explanatory variables
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)

#splitting into training and test data
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.5 , random_state = 0)

#initializing and training the logistic regression model
model = LogisticRegression()
model.fit(X_train, y_train)
print('Accuracy(train):{:.3f}'.format(model.score(X_train_std,y_train)))
print('Accuracy(test):{:.3f}'.format(model.score(X_test_std,y_test)))

Accuracy(train):0.755
Accuracy(test):0.751

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [ ]:
# checking the coefficinents for each variable
model.coef_

array([[ 5.580e-04, -3.264e-06, -5.110e-02,  3.292e-04,  7.768e-04,
        -2.041e-03]])

In [ ]:
# Decision Trees (Mushroom Data Set) Determining if a group of mushrooms are poisonous or not based on various attributes

#Retrieving the data
url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/mushroom/agaricus-lepiota.data'
res = requests.get(url).content

#Loading the retrieved data into a DataFrame object
mushroom= pd.read_csv(io.StringIO(res.decode('utf-8')), header=None)

#setting coloumns labels
mushroom.columns = [  'classes', 'cap_shape', 'cap_surface', 'cap_color', 'bruises', 'odor',
                       'gill_attachment','gill_spacing','gill_size','gill_color','stalk_shape',
                        'stalk_root','stalk_surface_above_ring','stalk_surface_below_ring',
                        'stalk_color_above_ring','stalk_color_below_ring','veil_type','veil_color',
                        'ring_number','ring_type','spore_print_color','population', 'habitat']
# Displaying the first 5 rows
mushroom.head()

,classes,cap_shape,cap_surface,cap_color,bruises,odor,gill_attachment,gill_spacing,gill_size,gill_color,...,stalk_surface_below_ring,stalk_color_above_ring,stalk_color_below_ring,veil_type,veil_color,ring_number,ring_type,spore_print_color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [ ]:
print('Data shape:{}'.format(mushroom.shape))
print('Number of missing values:{}'.format(mushroom.isnull()))

Data shape:(8124, 23)
Number of missing values:      classes  cap_shape  cap_surface  cap_color  bruises   odor  \
0       False      False        False      False    False  False
1       False      False        False      False    False  False
2       False      False        False      False    False  False
3       False      False        False      False    False  False
4       False      False        False      False    False  False
...       ...        ...          ...        ...      ...    ...
8119    False      False        False      False    False  False
8120    False      False        False      False    False  False
8121    False      False        False      False    False  False
8122    False      False        False      False    False  False
8123    False      False        False      False    False  False

      gill_attachment  gill_spacing  gill_size  gill_color  ...  \
0               False         False      False       False  ...
1               False         False      False       False  ...
2               False         False      False       False  ...
3               False         False      False       False  ...
4               False         False      False       False  ...
...               ...           ...        ...         ...  ...
8119            False         False      False       False  ...
8120            False         False      False       False  ...
8121            False         False      False       False  ...
8122            False         False      False       False  ...
8123            False         False      False       False  ...

      stalk_surface_below_ring  stalk_color_above_ring  \
0                        False                   False
1                        False                   False
2                        False                   False
3                        False                   False
4                        False                   False
...                        ...                     ...
8119                     False                   False
8120                     False                   False
8121                     False                   False
8122                     False                   False
8123                     False                   False

      stalk_color_below_ring  veil_type  veil_color  ring_number  ring_type  \
0                      False      False       False        False      False
1                      False      False       False        False      False
2                      False      False       False        False      False
3                      False      False       False        False      False
4                      False      False       False        False      False
...                      ...        ...         ...          ...        ...
8119                   False      False       False        False      False
8120                   False      False       False        False      False
8121                   False      False       False        False      False
8122                   False      False       False        False      False
8123                   False      False       False        False      False

      spore_print_color  population  habitat
0                 False       False    False
1                 False       False    False
2                 False       False    False
3                 False       False    False
4                 False       False    False
...                 ...         ...      ...
8119              False       False    False
8120              False       False    False
8121              False       False    False
8122              False       False    False
8123              False       False    False

[8124 rows x 23 columns]

In [ ]:
# Data organization into four explanatory variables
# Using dummy encoding to change all the variables into numerical values

mushroom_dummy = pd.get_dummies(mushroom[['gill_color','gill_attachment','odor','cap_color']], dtype = 'int')
mushroom_dummy.head()

# if its gill_colour 1 to represent black and 0 to represent the other

#Also converting the target variable since it is categorrical
mushroom_dummy['flg'] = mushroom['classes'].map(lambda x: 1 if x == 'p' else 0)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

#data split
X=mushroom_dummy.drop('flg',axis =1)
Y=mushroom_dummy['flg']
x_train, x_test , y_train , y_test = train_test_split(X ,Y ,test_size=0.2 ,random_state=0)

#intialize and train the decision tree classifier
model = DecisionTreeClassifier(criterion='entropy',max_depth=3,random_state=0)
model.fit(x_train,y_train)

print('Accuracy(train):{:.3f}'.format(model.score(x_train,y_train)))
print('Accuracy(test):{:.3f}'.format(model.score(x_test,y_test)))

Accuracy(train):0.991
Accuracy(test):0.993